# Generated by Django 3.0.2 on 2020-01-05 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='udata',
            name='ever_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='udata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='u', to=settings.AUTH_USER_MODEL),
        ),
    ]
