# Generated by Django 2.2.3 on 2020-01-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udata',
            name='resign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
